In [24]:
import torch
import numpy as np

In [26]:
# check if cuda is avaiable on your pc or gpu
torch.cuda.is_available()

False

In [3]:
xcode-select --install


NameError: name 'xcode' is not defined

In [4]:
some_data = [[1,2],[3,4]]

In [5]:
some_data

[[1, 2], [3, 4]]

In [6]:
type(some_data)

list

In [7]:
np.array(some_data)

array([[1, 2],
       [3, 4]])

In [8]:
np.asarray(some_data)

array([[1, 2],
       [3, 4]])

In [10]:
some_data = torch.tensor(some_data)

In [11]:
type(some_data)

torch.Tensor

In [12]:
some_data.dtype

torch.int64

In [13]:
numpy_array = np.random.rand(3,4)

In [14]:
numpy_array

array([[0.34446711, 0.40956628, 0.31878188, 0.23938628],
       [0.68051416, 0.56053648, 0.55649867, 0.72172842],
       [0.97507901, 0.5192625 , 0.22428084, 0.05076476]])

In [15]:
torch.from_numpy(numpy_array)

tensor([[0.3445, 0.4096, 0.3188, 0.2394],
        [0.6805, 0.5605, 0.5565, 0.7217],
        [0.9751, 0.5193, 0.2243, 0.0508]], dtype=torch.float64)

In [16]:
torch.tensor(numpy_array)

tensor([[0.3445, 0.4096, 0.3188, 0.2394],
        [0.6805, 0.5605, 0.5565, 0.7217],
        [0.9751, 0.5193, 0.2243, 0.0508]], dtype=torch.float64)

In [27]:
torch.ones(3, 4)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [28]:
torch.zeros(3,4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [29]:
my_tensor = torch.rand(3, 4)

Tensors are arrays that can be kept in CPU or GPU memory. 

In [30]:
my_tensor.dtype

torch.float32

In [31]:
my_tensor.device

device(type='cpu')

In [33]:
my_tensor.to("metal")

RuntimeError: Expected one of cpu, cuda, ipu, xpu, mkldnn, opengl, opencl, ideep, hip, ve, fpga, ort, xla, lazy, vulkan, mps, meta, hpu, mtia, privateuseone device type at start of device string: metal

In [35]:
if torch.backends.mps.is_available():
    mps_device = torch.device("mps")

In [36]:
my_tensor = torch.rand(3, 4)

In [37]:
my_tensor.device

device(type='cpu')

In [40]:
my_tensor.to("mps")

tensor([[0.5835, 0.0059, 0.1071, 0.5829],
        [0.4313, 0.4089, 0.8736, 0.3370],
        [0.6631, 0.1127, 0.2892, 0.1013]], device='mps:0')

In [41]:
my_tensor.device

device(type='cpu')